# Exported from Render on 2024-09-18T23:57:34Z
databases:
- name: alejandras-blog
  databaseName: alejandras_blog
  user: alex
  plan: starter
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
